### ISSUE TITLE
new demo theme does not work 

### ISSUE THREAD

**Issue by jtorresfabra** [documentationjs/grunt-documentation#8]
Hi @SunboX, I just tried your new theme example but it fails for me:
doing $grunt --stack --verbose

trace:

```
Initializing
Command-line options: --stack, --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Initializing config...OK

Registering "../../tasks" tasks.
Loading "documentation.js" tasks...OK
+ documentation
Loading "Gruntfile.js" tasks...OK
+ default

No tasks specified, running default tasks.
Running tasks: default

Running "default" task

Running "documentation" task

Running "documentation:default" (documentation) task
Verifying property documentation.default exists in config...OK
Files: src/ColorPoint.js -> ColorPoint.js
Files: src/Point.js -> Point.js
Options: format="html", shallow=false, github=false, access=["public","protected","undefined"], order=[], destination="docs", theme="/home/jtorres/Projects/grunt-documentation/demo/theme/documentation-theme-light"
>> TypeError: object is not a function
Warning: Task "documentation:default" failed. Use --force to continue.
Error: Task "documentation:default" failed.
    at Task.<anonymous> (/home/jtorres/Projects/grunt-documentation/demo/theme/node_modules/grunt/lib/util/task.js:205:15)
    at null._onTimeout (/home/jtorres/Projects/grunt-documentation/demo/theme/node_modules/grunt/lib/util/task.js:241:33)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

Aborted due to warnings.
```

**Comment by SunboX** [comment]
Hey @jtorresfabra, I think this is related to https://github.com/documentationjs/documentation-theme-light/issues/3

**Comment by jtorresfabra** [comment]
Hey @SunboX 

I just investigated a bit and it seems the error is in 
https://github.com/documentationjs/documentation/blob/master/lib/output/html.js#L35

as theme is an object instead of a function due to index.js being void. 

Better said, the error is in the index.js of the template, it can not be void.
